language: vim

before_script: |
  sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
  sudo apt-get install ipython libzmq-dev python-dev
  sudo easy_install -q pyzmq
  git clone https://github.com/junegunn/vader.vim.git
  hg clone https://code.google.com/p/vim/
  cd vim
  ./configure --with-features=huge --enable-pythoninterp
  make
  sudo make install
  cd -
  sudo pip install -U ipython

script: |
  /usr/local/bin/vim -Nu <(cat << VIMRC
  filetype off
  set rtp+=vader.vim
  set rtp+=.
  filetype plugin indent on
  VIMRC) -c 'Vader! test/*' > /dev/null
