language: vim

before_script: |
  git clone https://github.com/junegunn/vader.vim.git
  sudo apt-get install vim-nox ipython python-zmq

script: |
  vim -Nu <(cat << VIMRC
  filetype off
  set rtp+=vader.vim
  set rtp+=.
  set rtp+=after
  filetype plugin indent on
  VIMRC) -c 'Vader! test/*' > /dev/null
