language: vim

before_script: |
  sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
  sudo apt-get install vim-nox ipython libzmq-dev
  sudo easy_install -q pyzmq
  git clone https://github.com/junegunn/vader.vim.git
  echo "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  vim  -c "echo has('python')" -c "quit"
  echo "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

script: |
  vim -Nu <(cat << VIMRC
  filetype off
  set rtp+=vader.vim
  set rtp+=.
  set rtp+=after
  filetype plugin indent on
  VIMRC) -c 'Vader! test/*'
  # > /dev/null
